"""Create tables and other changes

Revision ID: 0c6ecd02c057
Revises: 36789511da64
Create Date: 2025-06-14 11:29:04.188968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c6ecd02c057'
down_revision: Union[str, None] = '36789511da64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histori',
    sa.Column('id_histori', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_diagnosa', sa.Integer(), nullable=False),
    sa.Column('jenis_penyakit', sa.String(), nullable=False),
    sa.Column('rekomendasi', sa.Text(), nullable=False),
    sa.Column('tanggal_update', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_diagnosa'], ['diagnosa.id_diagnosa'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_histori')
    )
    op.drop_index('ix_statistik_id_statistik', table_name='statistik')
    op.drop_table('statistik')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistik',
    sa.Column('id_statistik', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tanggal', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_sehat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_kuning', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_keriting', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], name='statistik_id_user_fkey'),
    sa.PrimaryKeyConstraint('id_statistik', name='statistik_pkey')
    )
    op.create_index('ix_statistik_id_statistik', 'statistik', ['id_statistik'], unique=False)
    op.drop_table('histori')
    # ### end Alembic commands ###
