"""tambah histori baru

Revision ID: 630c44528c97
Revises: 0c6ecd02c057
Create Date: 2025-06-14 23:43:52.303636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630c44528c97'
down_revision: Union[str, None] = '0c6ecd02c057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histori', sa.Column('image', sa.String(), nullable=True))
    op.add_column('histori', sa.Column('kategori', sa.String(), nullable=True))
    op.add_column('histori', sa.Column('akurasi', sa.Float(), nullable=True))
    op.drop_constraint('histori_id_user_fkey', 'histori', type_='foreignkey')
    op.drop_column('histori', 'id_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histori', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('histori_id_user_fkey', 'histori', 'users', ['id_user'], ['id_user'])
    op.drop_column('histori', 'akurasi')
    op.drop_column('histori', 'kategori')
    op.drop_column('histori', 'image')
    # ### end Alembic commands ###
