"""create tables

Revision ID: 66e9b9eca04d
Revises: 
Create Date: 2025-05-06 17:06:31.045260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e9b9eca04d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artikel',
    sa.Column('id_artikel', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('isi', sa.String(), nullable=False),
    sa.Column('penulis', sa.String(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=False),
    sa.Column('gambar', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_artikel')
    )
    op.create_index(op.f('ix_artikel_id_artikel'), 'artikel', ['id_artikel'], unique=False)
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_table('diagnosa',
    sa.Column('id_diagnosa', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('jenis_penyakit', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('rekomendasi', sa.String(), nullable=True),
    sa.Column('kategori', sa.Enum('SEHAT', 'KUNING', 'KERITING', name='kondisidaun'), nullable=True),
    sa.Column('akurasi', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_diagnosa')
    )
    op.create_index(op.f('ix_diagnosa_id_diagnosa'), 'diagnosa', ['id_diagnosa'], unique=False)
    op.create_table('statistik',
    sa.Column('id_statistik', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('total_sehat', sa.Integer(), nullable=True),
    sa.Column('total_kuning', sa.Integer(), nullable=True),
    sa.Column('total_keriting', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_statistik')
    )
    op.create_index(op.f('ix_statistik_id_statistik'), 'statistik', ['id_statistik'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistik_id_statistik'), table_name='statistik')
    op.drop_table('statistik')
    op.drop_index(op.f('ix_diagnosa_id_diagnosa'), table_name='diagnosa')
    op.drop_table('diagnosa')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_artikel_id_artikel'), table_name='artikel')
    op.drop_table('artikel')
    # ### end Alembic commands ###
