"""tambah kolom create_date, update_date dan google_id di users

Revision ID: 888e32368b67
Revises: 66e9b9eca04d
Create Date: 2025-05-09 18:36:53.220187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888e32368b67'
down_revision: Union[str, None] = '66e9b9eca04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artikel', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('artikel', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('diagnosa', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('diagnosa', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('statistik', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('statistik', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'update_date')
    op.drop_column('users', 'create_date')
    op.drop_column('users', 'google_id')
    op.drop_column('statistik', 'update_date')
    op.drop_column('statistik', 'create_date')
    op.drop_column('diagnosa', 'update_date')
    op.drop_column('diagnosa', 'create_date')
    op.drop_column('artikel', 'update_date')
    op.drop_column('artikel', 'create_date')
    # ### end Alembic commands ###
