"""Remove histori table and update diagnosa model

Revision ID: b081aabe3286
Revises: 73fd29d7a5d8
Create Date: 2025-06-17 23:13:37.891352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b081aabe3286'
down_revision: Union[str, None] = '73fd29d7a5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histori')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histori',
    sa.Column('id_histori', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_diagnosa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jenis_penyakit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rekomendasi', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tanggal_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kategori', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('akurasi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_diagnosa'], ['diagnosa.id_diagnosa'], name='histori_id_diagnosa_fkey'),
    sa.PrimaryKeyConstraint('id_histori', name='histori_pkey')
    )
    # ### end Alembic commands ###
