"""table-capstone

Revision ID: 710afc65e73c
Revises: 
Create Date: 2025-04-25 20:30:45.558213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710afc65e73c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('diagnosa',
    sa.Column('id_diagnosa', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('jenis_penyakit', sa.String(length=100), nullable=False),
    sa.Column('image_path', sa.String(length=200), nullable=False),
    sa.Column('hasil', sa.String(length=100), nullable=False),
    sa.Column('akurasi', sa.Float(), nullable=True),
    sa.Column('rekomendasi', sa.Text(), nullable=True),
    sa.Column('solusi', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['Users.id_user'], ),
    sa.PrimaryKeyConstraint('id_diagnosa')
    )
    op.create_table('grafikdiagnosa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('total_scan', sa.Integer(), nullable=True),
    sa.Column('jumlah_sehat', sa.Integer(), nullable=True),
    sa.Column('jumlah_kuning', sa.Integer(), nullable=True),
    sa.Column('jumlah_keriting', sa.Integer(), nullable=True),
    sa.Column('rentang_waktu', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['Users.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grafikdiagnosa')
    op.drop_table('diagnosa')
    op.drop_table('Users')
    # ### end Alembic commands ###
